### PR TITLE
Update PolicyEngine US to 1.44.1

### PR DESCRIPTION
**Pull request by nikhilwoodruff**
Update PolicyEngine US to 1.44.1

### CODE REVIEW

**Comment by CalebPena** [comment]
@MaxGhenis can we merge this?

**Comment by MaxGhenis** [comment]
Sorry for the delay - could we merge early next week? @anth-volk is out today and I'd want to check with him on the Python version update to ensure we don't need any GCP-level action https://github.com/PolicyEngine/policyengine-household-api/issues/219

**Comment by anth-volk** [comment]
There are a couple of updates the household API will need to be Python 3.10-ready, but can definitely be done early this week, as described.

**Comment by anth-volk** [comment]
Household API is now updated

**Pull request closed without merging**
